name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  # Remove unused Firebase packages if you're not using them
  # firebase_core: ^2.24.2
  # firebase_storage: ^11.6.0
  # firebase_auth: ^4.16.0
  # cloud_firestore: ^4.14.0
  # Keep only what's needed for Cloudinary
  cloudinary_public: ^0.21.0  # Add this line
  cloudinary_url_gen: ^1.8.0      # For URL generation (optional)

   
  http_parser: ^4.0.2 
  path: ^1.8.3
  mime: ^1.0.4
  cloudinary_flutter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/vintage_newspaper.jpg